//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgTable
    {
        public int Id { get; set; }
        public string FromUserName { get; set; }
        public string ToUserName { get; set; }
        public string MsgText { get; set; }
        public System.DateTime MsgDate { get; set; }
    }
}
