//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientTable()
        {
            this.AppointmentTables = new HashSet<AppointmentTable>();
        }
    
        public int PatientID { get; set; }
        public string UserName { get; set; }
        public string PatientName { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTable> AppointmentTables { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
